allowBuilds:
  better-sqlite3: set this to true or false
  electron: set this to true or false
  electron-overlay-window: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  tesseract.js: set this to true or false
  unrs-resolver: set this to true or false
