import { buildForbiddenJewelIdentifier, buildGemPriceIdentifier, buildIncursionRoomIdentifier } from './identities';
import type { PoeNinjaCategory, PoeNinjaCategoryDefinition } from './catalog';
import type { LegacyPriceSnapshot, PriceIndex } from './types';

type PoeNinjaResponse = { lines?: any[]; items?: any[] };
function setPrice(index: PriceIndex, identifier: string | undefined, value: unknown) { if (!identifier || typeof value !== 'number' || !Number.isFinite(value)) return; index[identifier] = index[identifier] === undefined ? value : Math.max(index[identifier], value); }
function exchange(response: PoeNinjaResponse) { const result: PriceIndex = {}; const names = new Map((response.items ?? []).map((item) => [item.id, item.name])); for (const line of response.lines ?? []) setPrice(result, names.get(line.id) ?? line.name, line.primaryValue); return result; }
function baseType(response: PoeNinjaResponse) { const result: PriceIndex = {}; for (const line of response.lines ?? []) setPrice(result, `${line.name} L${line.levelRequired}${line.variant ? ` ${line.variant}` : ''}`, line.chaosValue); return result; }
function wombgift(response: PoeNinjaResponse) { const result: PriceIndex = {}; for (const line of response.lines ?? []) setPrice(result, `${line.name} L${line.levelRequired}`, line.chaosValue); return result; }
function item(response: PoeNinjaResponse) { const result: PriceIndex = {}; for (const line of response.lines ?? []) { let identifier = line.name; if (line.links === 6) identifier += ' 6L'; else if (line.gemLevel) identifier = buildGemPriceIdentifier(line.name, line.gemLevel, line.gemQuality ?? 0, Boolean(line.corrupted)); else if (line.baseType?.includes('Cluster Jewel') && line.variant) identifier += ` L${line.levelRequired} ${line.variant.split(' ')[0]}P`; else if (line.variant) identifier += ` (${line.variant})`; setPrice(result, identifier, line.chaosValue); } return result; }
function map(response: PoeNinjaResponse) { const result: PriceIndex = {}; for (const line of response.lines ?? []) setPrice(result, `${line.name}${line.variant ? ` ${String(line.variant).replace(', ', '')}` : ''}`, line.chaosValue); return result; }
function uniqueMap(response: PoeNinjaResponse) { const result: PriceIndex = {}; for (const line of response.lines ?? []) setPrice(result, line.name, line.chaosValue); return result; }
function forbiddenJewel(response: PoeNinjaResponse) { const result: PriceIndex = {}; for (const line of response.lines ?? []) { const passive = line.metadata?.passiveName ?? line.name; if (typeof line.variant === 'string' && typeof passive === 'string') setPrice(result, buildForbiddenJewelIdentifier(line.variant, passive), line.chaosValue); } return result; }
function beast(response: PoeNinjaResponse) { return uniqueMap(response); }
function valdoMap(response: PoeNinjaResponse) { const result: PriceIndex = {}; const ambiguous = new Set<string>(); for (const line of response.lines ?? []) { if (ambiguous.has(line.name)) continue; if (result[line.name] !== undefined) { delete result[line.name]; ambiguous.add(line.name); } else setPrice(result, line.name, line.chaosValue); } return result; }
function incursionTemple(response: PoeNinjaResponse) { const result: PriceIndex = {}; for (const line of response.lines ?? []) { const match = String(line.name ?? '').match(/^(.*) \(Tier (\d+)\)$/); setPrice(result, match ? buildIncursionRoomIdentifier(match[1], Number(match[2])) : line.name, line.chaosValue); } return result; }
const adapters = { exchange, baseType, wombgift, item, map, uniqueMap, forbiddenJewel, beast, valdoMap, incursionTemple };
export function adaptPoeNinjaResponse(definition: PoeNinjaCategoryDefinition, response: PoeNinjaResponse): PriceIndex { return adapters[definition.adapter](response); }
export function assembleLegacySnapshot(categories: Partial<Record<PoeNinjaCategory, PriceIndex>>, definitions: Readonly<Record<PoeNinjaCategory, PoeNinjaCategoryDefinition>>): LegacyPriceSnapshot { const snapshot: LegacyPriceSnapshot = {}; for (const [category, index] of Object.entries(categories)) { if (index) Object.assign(snapshot[definitions[category as PoeNinjaCategory].destination] ??= {}, index); } return snapshot; }
